[package]
name = "source"
version = "0.1.0"
edition = "2024"

[dependencies]
domain = { path = "../domain" }
document = { path = "../document" }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
ulid = { workspace = true }
walkdir = { workspace = true }

[dev-dependencies]
tempfile = "3"
