[package]
name = "web"
version = "0.1.0"
edition = "2024"

[lib]
name = "web"
path = "src/lib.rs"

[dependencies]
anyhow = "1"
application = { path = "../application" }
axum = { version = "0.7", default-features = false, features = ["http1", "http2", "query", "matched-path", "tokio"] }
bytes = "1"
clap = { workspace = true }
config = { path = "../config" }
domain = { path = "../domain" }
preview = { path = "../preview" }
rusqlite = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
storage = { path = "../storage" }
thiserror = { workspace = true }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "net", "signal", "sync"] }
tower-http = { version = "0.5", features = ["trace", "normalize-path"] }
tracing = "0.1"
ulid = { workspace = true }

[build-dependencies]